In [2]:
## Input x as a matrix
## and then set "s" value as null
## then I changed reference from "mean" to "solve"

In [3]:
makeCacheMatrix <- function(x = matrix(sample(1:100,9),3,3)) {
  s <- NULL
  set <- function(y) {
    x <<- y
    s <<- NULL
  }
  get <- function() x
  setsolve <- function(solve) s <<- solve
  getsolve <- function() s
  list(set = set, get = get,
       setsolve = setsolve,
       getsolve = getsolve)
}

In [4]:
## Similarly, changed "mean" to "solve".
cacheSolve <- function(x, ...) {
  s <- x$getsolve()
  if(!is.null(s)) {
    message("Inversed Matrix")
    return(s)
  }
  data <- x$get()
  s <- solve(data, ...)
  x$setsolve(s)
  s
}

## Our aim is to write a pair of functions, namely, "makeCacheMatrix" and "cacheSolve" that cache the inverse of a matrix

## makeCacheMatrix is a function which creates a special "matrix" object that can cache its inverse for the input.

In [5]:
makeCacheMatrix <- function(x = matrix()) {

inv <- NULL
set <- function(y) {
x <<- y
inv <<- NULL
}
get <- function() x
setinv <- function(inverse) inv <<- inverse
getinv <- function() inv
list(set = set, get = get, setinv = setinv, getinv = getinv)
}

## CacheSolve is a function which computes the inverse of the special "matrix" returned by makeCacheMatrix above. If the inverse has already been calculated, then the cachesolve should retrieve the inverse from the cache.

In [6]:
cacheSolve <- function(x, ...) {
## Return a matrix that is the inverse of 'x'
inv <- x$getinv()
if(!is.null(inv)) {
message("getting cached result")
return(inv)
}
data <- x$get()
inv <- solve(data, ...)
x$setinv(inv)
inv
}

In [7]:
m <- matrix(rnorm(16),4,4)
m1 <- makeCacheMatrix(m)
cacheSolve(m1)

[,1]        [,2]       [,3]        [,4]      
[1,]  0.02051121 -0.6607326  0.05388656  0.2158500
[2,]  1.08677588 -0.3911602  0.40524185  0.2449156
[3,] -0.05750143 -0.1445250  0.27654390  0.3725861
[4,]  0.34273597  1.5545848 -0.81929860 -0.1392084

## Caching the Inverse of a Matrix: Matrix inversion is usually a costly computation and there may be some benefit to caching the inverse of a matrix rather than compute it repeatedly.
## Below are a pair of functions that are used to create a special object that stores a matrix and caches its inverse. This function creates a special "matrix" object that can cache its inverse.

In [8]:
makeCacheMatrix <- function(x = matrix()) {
inv <- NULL
set <- function(y) {
x <<- y
inv <<- NULL
}
get <- function() x
setInverse <- function(inverse) inv <<- inverse
getInverse <- function() inv
list(set = set,
get = get,
setInverse = setInverse,
getInverse = getInverse)
}

## This function computes the inverse of the special "matrix" created by makeCacheMatrix above. If the inverse has already been calculated (and the matrix has not changed), then it should retrieve the inverse from the cache.

In [9]:
cacheSolve <- function(x, ...) {
## Return a matrix that is the inverse of 'x'
inv <- x$getInverse()
if (!is.null(inv)) {
message("getting cached data")
return(inv)
}
mat <- x$get()
inv <- solve(mat, ...)
x$setInverse(inv)
inv
}

In [ ]:
# Testing
source("ProgrammingAssignment2/cachematrix.R")

In [11]:
my_matrix <- makeCacheMatrix(matrix(1:4, 2, 2))
my_matrix$get()

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [13]:
my_matrix$getInverse()


NULL

In [14]:
cacheSolve(my_matrix)

[,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5

In [16]:

my_matrix$getInverse()

[,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5

In [17]:
my_matrix$set(matrix(c(2, 2, 1, 4), 2, 2))

In [18]:
my_matrix$get()

[,1] [,2]
[1,] 2    1   
[2,] 2    4

In [19]:
my_matrix$getInverse()


NULL

In [20]:
cacheSolve(my_matrix)

[,1]       [,2]      
[1,]  0.6666667 -0.1666667
[2,] -0.3333333  0.3333333

In [22]:
cacheSolve(my_matrix)


getting cached data



[,1]       [,2]      
[1,]  0.6666667 -0.1666667
[2,] -0.3333333  0.3333333

In [23]:
my_matrix$getInverse()

[,1]       [,2]      
[1,]  0.6666667 -0.1666667
[2,] -0.3333333  0.3333333